---
computer: pias
label: quad-1.0
description: Solve the quadratic equation
filepath_executable: /share/data/hungdt/aiida/quad/quad
default_calc_job_plugin: quad-calculation
use_double_quotes: no
with_mpi: no